# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's source code from your host to your container's /app directory
COPY . .

# Cloud Run will set the PORT environment variable
# The application should listen on this port
ENV PORT 8080

# Run the Flask app
# Use gunicorn or similar for production for better performance and robustness
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 main:app